vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        ns_img:
            uri_prefix: /public/images/ns_img_content
            upload_destination: '%kernel.project_dir%/public/images/ns_img_content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        ns_icon:
            uri_prefix: /public/images/ns_icon
            upload_destination: '%kernel.project_dir%/public/images/ns_icon'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
